In [1]:
import numpy as np 
import pims
import skimage as ski 
import matplotlib as mpl
from matplotlib import pyplot as plt
%matplotlib inline
import pandas as pd
import trackpy as tp
from trackpy import predict
import pickle
import linking_3d as l3d
import time 
import background_subtraction as bs
import visualization as vs
import fast_cost_mat as fcm # works ! need to comment. fucked up in there... 
#tweak plot styles
mpl.rc('figure',  figsize=(15, 6))
mpl.rc('image', cmap='gray')
#tp.ignore_logging() # important to not spam too much print output 

In [2]:
#run these if you want to reload imported modules every time the code is run 
%load_ext autoreload
%autoreload 2

In [3]:
# load in the trajectories to link 
f = open('../trajectories/tLi-pickle','rb') # these are the interpolated trajectories 
tL = pickle.load(f)
f.close()
f = open('../trajectories/tRi-pickle','rb') 
tR = pickle.load(f)
f.close()

In [49]:
nl = nr = 1000

In [52]:
a = np.zeros((5,5))
b = np.ones((5,5))*4
c = np.ones((5,5))
d = np.ones((5,5))*2

Zc = np.stack((a,b,c,d))


In [58]:
np.where(Zc==np.ones(Zc[0].shape))

(array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2]),
 array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4,
        4, 4]),
 array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2,
        3, 4]))

In [54]:
for i in range(len(Zc)):
    a = np.ones(Zc[i].shape)
    b = Zc[i]
    if np.array_equal(a,b):
        print(i)
    else:
        pass 

2


In [53]:
Zc

array([[[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 2.,  2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.,  2.]]])

In [50]:
costs = fcm.gen_cost_mat(tL[:nl],tR[:nr]) 

2000 x 2000 cost matrix generated in 2 seconds


In [51]:
link_inds = fcm.cython_link(costs,nl,nr)

256 links generated from 1000 possibilities in 335 seconds with CYTHON.


In [48]:
tracks = l3d.links_to_tracks(link_inds,tL[:500],tR[:500])

KeyboardInterrupt: 

In [ ]:
im = vs.draw_many_tracks(None,None,tracks,range(140,164))
plt.imshow(im)